// <auto-generated />
using System;
using Loyalty.Api.Modules.RewardOrders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Loyalty.Api.Modules.RewardOrders.Migrations
{
    [DbContext(typeof(RewardOrdersDbContext))]
    [Migration("20260201121000_AddRewardOrderTenantCreatedAtIndex")]
    partial class AddRewardOrderTenantCreatedAtIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Loyalty.Api.Modules.RewardOrders.Domain.RewardOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PlacedOnBehalf")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("RewardOrders", (string)null);
                });

            modelBuilder.Entity("Loyalty.Api.Modules.RewardOrders.Domain.RewardOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RewardOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RewardProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardVendor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RewardOrderId");

                    b.ToTable("RewardOrderItems", (string)null);
                });

            modelBuilder.Entity("Loyalty.Api.Modules.RewardOrders.Domain.RewardOrderItem", b =>
                {
                    b.HasOne("Loyalty.Api.Modules.RewardOrders.Domain.RewardOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("RewardOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Api.Modules.RewardOrders.Domain.RewardOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
